org: andresmars25
app: repositorio-datos
service: repositorio-datos
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x

functions:
  status:
    handler: functions/status.handler
    events:
      - http:
          method: GET
          path: /

  register:
    handler: functions/register.handler
    events:
      - http:
          method: POST
          path: /register

  login:
    handler: functions/login.handler
    events:
      - http:
          method: POST
          path: /login

  getDepartamentos:
    handler: functions/get/departamentos.handler
    events:
      - http:
          method: GET
          path: /departamentos
  getDepartamento:
    handler: functions/get/departamento.handler
    events:
      - http:
          method: GET
          path: /departamento/{divipola}
  postDepartamentos:
    handler: functions/post/departamentos.handler
    events:
      - http:
          method: POST
          path: /departamentos
  postDepartamento:
    handler: functions/post/departamento.handler
    events:
      - http:
          method: POST
          path: /departamento
  
  getMunicipios:
    handler: functions/get/municipios.handler
    events:
      - http:
          method: GET
          path: /municipios
  postMunicipios:
    handler: functions/post/municipios.handler
    events:
      - http:
          method: POST
          path: /municipios
  postMunicipio:
    handler: functions/post/municipio.handler
    events:
      - http:
          method: POST
          path: /municipio

  getRegiones:
    handler: functions/get/regiones.handler
    events:
      - http:
          method: GET
          path: /regiones
  postRegiones:
    handler: functions/post/regiones.handler
    events:
      - http:
          method: POST
          path: /regiones
  postRegion:
    handler: functions/post/region.handler
    events:
      - http:
          method: POST
          path: /region

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'